version: '3'
services:
  media-job-loop:
    image: node:carbon
    container_name: media.job-loop
    command: bash -c "tail -f /dev/null"
    working_dir: /usr/src
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    ports:
      - "3006:3006"
    networks:
      infra_cdn:
        aliases:
          - media-job-loop

networks:
  infra_cdn:
    external: true
